### PR TITLE
Update Main Process

### PR DESCRIPTION
**Pull request by KorbsStudio**
**Changelog**:
 - Update Electron from v11 to v18
 - Add build icons
 - Remove all items from alt menu
 - Set min-height and min-width for the main window
 - Update splash window
   - Change background and add transparent logo
   - Add round corners for splash
   - Skip Windows taskbar for splash
   - Prevent splash from being resized, maximized, and minimized

### CODE REVIEW

**Comment by EmperorBale** [comment]
Hi, sorry for late reply. First of all thank you for putting all this work into improving our client. 

This PR has a lot of changes and I haven't reviewed them all yet, but i'm curious how you got flash player working on Electron v18? From my understanding Electron dropped support for flash player a while ago, but I wouldn't be surprised if there was actually a way to workaround this that we didn't know about when we made the client. 

The second thing is that if we do merge this PR, we will merge into our private repository for the source code, so I want you to be aware of that.

**Comment by KorbsStudio** [comment]
Yeah, to be clear this is as far as I can get into the New Club Penguin, it seems you don't allow custom domain emails, `@korbsstudio.com` is used for my primary email. It also seems you don't allow OnMail as well. You need to extend your email whitelist. 
image

**Comment by iContinux** [comment]
We've been slowly increasing the email support.

As said above, how did you get Flash working on Electron 18? We didn't look much into it so there very well could be something simple we missed. lol

**Comment by EmperorBale** [comment]
> Yeah, to be clear this is as far as I can get into the New Club Penguin, it seems you don't allow custom domain emails, `@korbsstudio.com` is used for my primary email. It also seems you don't allow `@onmail.com` as well. You need to extend your email whitelist.
> 
> image

You should still be able to get to the flash player even without an account. We also allow users who did not verify their email to play the game for 7 days, so feel free to use a random email address that uses a whitelisted domain for testing purposes.

**Comment by KorbsStudio** [comment]
Okay, so Flash is randomly working in v18 of Electron. I didn't really do anything to make sure it works, so "It Just Works".

**Comment by EmperorBale** [comment]
> Okay, so Flash is randomly working in v18 of Electron. I didn't really do anything to make sure it works, so "It Just Works".

That's surprising, were you able to login and join a server?

**Comment by KorbsStudio** [comment]
image
Nope ;-; maybe downgrade it to 16? idk when they dropped Flash.

**Comment by iContinux** [comment]
> image Nope ;-; maybe downgrade it to 16? idk when they dropped Flash.

They dropped support after V12. Hence why we are using V12

**Comment by EmperorBale** [comment]
I believe the last version that supported flash was `11.5.0` as flash was dropped in `12.0.0`.

**Comment by KorbsStudio** [comment]
Lemme double check everything then.

**Comment by KorbsStudio** [comment]
image
Did some exploring, also I forgot to enable plugins it. 
Final polishing up!

**Comment by KorbsStudio** [comment]
In the future, I may come back to add Settings. But, this will do for now.
Just did final testing, Flash Player is working with Electron 11.5.0!

**Comment by KorbsStudio** [comment]
Any updates?

**Comment by EmperorBale** [comment]
> Any updates?

Hi, sorry for the delay. We now have a new repository for the source code. We have also made changes since you made your changes, so you need to rebase your PR and reopen it in the new repository.

See the new repo here: https://github.com/New-Club-Penguin/NewCP-App

I am closing this PR so that you can create a new PR in that repo instead.

**Pull request closed without merging**
